Models/Slider.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EduHome.Models
{
    public class Slider:BaseEntity
    {
        [Required, StringLength(300)]
        public string Photo { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string ButtonText { get; set; }
    }
}

Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduHome.Areas.Admin.Helpers;
using EduHome.Areas.Admin.ViewModels;
using EduHome.DAL;
using EduHome.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EduHome.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public SliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            List<Slider> Sliders = await _context.Sliders.ToListAsync();
            return View(Sliders);
        }

        public IActionResult CreateSlider()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateSlider(SliderVM sliderVM)
        {
            if (!ModelState.IsValid) return View(sliderVM);

            var photo = sliderVM.Photo;

            if (photo == null)
            {
                ModelState.AddModelError("Photo", "Photo can not be empty");
                return View(sliderVM);
            }

            if (!FileHelper.CheckContent(photo.ContentType, "image/"))
            {
                ModelState.AddModelError("Photo", "Please select image format");
                return View(sliderVM);
            }

            if (!FileHelper.CheckLength(photo.Length, 200))
            {
                ModelState.AddModelError("Photo", "Image size must be less than 200kb");
                return View(sliderVM);
            }

            FileHelper.CreateFile(photo.FileName, _env.WebRootPath, "img", photo);

            Slider slider = new Slider
            {
                Text = sliderVM.Text,
                Title = sliderVM.Title,
                ButtonText = sliderVM.ButtonText,
                Photo = FileHelper.UniqueFileName
            };

            _context.Sliders.Add(slider);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EditSlider(int id)
        {
            var slider = await _context.Sliders.FirstOrDefaultAsync(s => s.Id == id);
            if (slider == null) return NotFound();
            SliderVM sliderVM = new SliderVM
            {
                Slider = slider,
                SliderId = slider.Id
            };

            return View(sliderVM);
        }

        [HttpPost]
        public async Task<IActionResult> EditSlider(SliderVM sliderVM)
        {
            var slider = await _context.Sliders.FirstOrDefaultAsync(s => s.Id == sliderVM.SliderId);
            if (slider == null) return NotFound();
            if (!ModelState.IsValid) return View(sliderVM);

            var photo = sliderVM.Photo;

            if(photo != null)
            {
                if (!FileHelper.CheckContent(photo.ContentType, "image/"))
                {
                    ModelState.AddModelError("Photo", "Please select image format");
                    return View(sliderVM);
                }

                if (!FileHelper.CheckLength(photo.Length, 200))
                {
                    ModelState.AddModelError("Photo", "Image size must be less than 200kb");
                    return View(sliderVM);
                }

                FileHelper.DeleteFile(slider.Photo, _env.WebRootPath, "img");
                FileHelper.CreateFile(sliderVM.Photo.FileName, _env.WebRootPath, "img", sliderVM.Photo);
                slider.Photo = FileHelper.UniqueFileName;
            }

            slider.Text = sliderVM.Text;
            slider.Title = sliderVM.Title;
            slider.ButtonText = sliderVM.ButtonText;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteSlider(int id)
        {
            var slider = await _context.Sliders.FirstOrDefaultAsync(s => s.Id == id);
            if (slider == null) return NotFound();
            _context.Sliders.Remove(slider);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/Slider/CreateSlider.cshtml
@model SliderVM

<div class="row justify-content-center">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create course</h4>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="Title">Title</label>
                        <input asp-for="Title" class="form-control" placeholder="Title">
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Text">Text</label>
                        <input asp-for="Text" class="form-control" placeholder="Text">
                        <span class="text-danger" asp-validation-for="Text"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ButtonText">Button text</label>
                        <input asp-for="ButtonText" class="form-control" placeholder="Button text">
                        <span class="text-danger" asp-validation-for="ButtonText"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo">Photo</label>
                        <img width="400px" src="" id="blah" />
                        <input asp-for="Photo" class="form-control" accept="image/*" placeholder="Photo" id="imgInp">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button asp-action="Index" class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>imgInp.onchange = evt => {
  const [file] = imgInp.files
  if (file) {
    blah.src = URL.createObjectURL(file)
  }
}</script>

Areas/Admin/Views/Slider/EditSlider.cshtml
@model SliderVM

<div class="row justify-content-center">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create course</h4>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <input hidden asp-for="SliderId" value="@Model.SliderId" />
                    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="Title">Title</label>
                        <input asp-for="Title" class="form-control" placeholder="Title" value="@Model.Slider.Title">
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Text">Text</label>
                        <input asp-for="Text" class="form-control" placeholder="Text" value="@Model.Slider.Text">
                        <span class="text-danger" asp-validation-for="Text"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ButtonText">Button text</label>
                        <input asp-for="ButtonText" class="form-control" placeholder="Button text" value="@Model.Slider.ButtonText">
                        <span class="text-danger" asp-validation-for="ButtonText"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo">Photo</label>
                        <img width="400px" src="~/img/@Model.Slider.Photo" id="blah" />
                        <input asp-for="Photo" class="form-control" accept="image/*" placeholder="Photo" id="imgInp">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button asp-action="Index" class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>imgInp.onchange = evt => {
  const [file] = imgInp.files
  if (file) {
    blah.src = URL.createObjectURL(file)
  }
}</script>

Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>

<a asp-controller="Slider" asp-action="CreateSlider" class="btn btn-success">Create</a>
<table class="table table-dark">
    <thead>
        <tr>
            <th> Slider Id</th>
            <th> Slider photo </th>
            <th> Delete </th>
            <th> Edit </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var slider in Model)
        {
            <tr>
                <td> @slider.Id </td>
                <td> <img src="~/img/@slider.Photo" /> </td>
                <td> <a asp-action="DeleteSlider" asp-route-id="@slider.Id" class="btn btn-danger"> Delete </a> </td>
                <td> <a asp-action="EditSlider" asp-route-id="@slider.Id" class="btn btn-primary"> Edit </a> </td>
            </tr>
        }
    </tbody>
</table>