Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EduHome.Models
{
    public class Category:BaseEntity
    {
        [Required]
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public IList<CourseCategory> CourseCategories { get; set; }
        public IList<EventCategory> EventCategories { get; set; }
        public IList<BlogCategory> BlogCategories { get; set; }
    }
}

Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduHome.Areas.Admin.ViewModels;
using EduHome.DAL;
using EduHome.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EduHome.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Category> Categories = await _context.Categories.Where(c=>c.IsDeleted==false).ToListAsync();      
            return View(Categories);
        }

        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategory(CategoryVM categoryVM)
        {
            if (!ModelState.IsValid) return View(categoryVM);

            List<Category> Categories = await _context.Categories.Where(c=>c.IsDeleted==false).ToListAsync();

            bool categoryExists = Categories.Exists(c => c.Name == categoryVM.Name);

            if (categoryExists)
            {
                ModelState.AddModelError("", "Category already exists");
                return View(categoryVM);
            }

            Category category = new Category { Name = categoryVM.Name, IsDeleted=false };

            _context.Categories.Add(category);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteCategory(int id)
        {
            var category = await _context.Categories.Where(c=>c.IsDeleted==false).FirstOrDefaultAsync(c => c.Id == id);
            if (category == null) return NotFound();
            category.IsDeleted = true;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EditCategory(int id)
        {
            var category = await _context.Categories.Where(c=>c.IsDeleted==false).FirstOrDefaultAsync(c => c.Id == id);
            if (category == null) return NotFound();
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> EditCategory(Category category)
        {
            if (!ModelState.IsValid) return View(category);
            var existingCategory = await _context.Categories.Where(c=>c.IsDeleted==false).FirstOrDefaultAsync(c => c.Id == category.Id);
            if (category == null) return NotFound();
            var categoryExists = await _context.Categories.FirstOrDefaultAsync(c => c.Name == category.Name);

            if (categoryExists!=null)
            {
                ModelState.AddModelError("", "Category already exists");
                return View(category);
            }
            existingCategory.Name = category.Name;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/Category/CreateCategory.cshtml
@model CategoryVM 

<div class="row justify-content-center">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create course</h4>
                <form class="forms-sample" method="post">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>                    
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button asp-action="Index" class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Category/EditCategory.cshtml
@model Category

<div class="row justify-content-center">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Edit category</h4>
                <form enctype="multipart/form-data" class="forms-sample" method="post">
                    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
                    <input hidden asp-for="Id" value="@Model.Id" />
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input asp-for="Name" class="form-control" value="@Model.Name" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button asp-action="Index" class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Category/Index.cshtml
@model List<Category>

<a asp-controller="Category" asp-action="CreateCategory" class="btn btn-success">Create</a>
<table class="table table-dark">
    <thead>
        <tr>
            <th> Category name</th>
            <th> Delete </th>
            <th> Edit </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var category in Model)
        {
            <tr>
                <td> @category.Name </td>
                <td> <a asp-action="DeleteCategory" asp-route-id="@category.Id" class="btn btn-danger"> Delete </a> </td>
                <td> <a asp-action="EditCategory" asp-route-id="@category.Id" class="btn btn-primary"> Edit </a> </td>
            </tr>
        }
    </tbody>
</table>